# Generated by Django 5.1.2 on 2024-10-11 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_contactmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactSubmission',
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(max_length=200),
        ),
    ]
