# Generated by Django 5.1.2 on 2024-10-14 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_authorprofile_journal'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='header',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='journal_images/'),
        ),
    ]
