# Generated by Django 5.1.2 on 2024-10-31 10:16

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_journal_header_journal_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='content',
        ),
        migrations.AddField(
            model_name='journal',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='journal_pdfs/'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='excerpt',
            field=ckeditor.fields.RichTextField(blank=True, help_text='You can format this text using the editor tools', max_length=1000),
        ),
    ]
