# Generated by Django 5.1.2 on 2024-10-31 10:22

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_journal_content_journal_pdf_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='excerpt',
            field=ckeditor.fields.RichTextField(blank=True, help_text='You can format this text using the editor tools'),
        ),
    ]
