# Generated by Django 5.1.2 on 2024-11-10 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='apa_citation',
            field=models.TextField(blank=True, help_text='APA format citation'),
        ),
        migrations.AddField(
            model_name='journal',
            name='chicago_citation',
            field=models.TextField(blank=True, help_text='Chicago format citation'),
        ),
        migrations.AddField(
            model_name='journal',
            name='mla_citation',
            field=models.TextField(blank=True, help_text='MLA format citation'),
        ),
    ]
