# Generated by Django 5.1.2 on 2024-11-15 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_journal_apa_citation_journal_chicago_citation_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactMessage',
        ),
    ]
