# Generated by Django 4.2.10 on 2026-09-03 17:42

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_delete_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, max_length=320, unique=True)),
                ('authors', models.CharField(help_text='Enter author names as they should appear in the publication.', max_length=500)),
                ('publication_date', models.DateField(default=django.utils.timezone.now)),
                ('category', models.CharField(blank=True, max_length=120)),
                ('report_number', models.CharField(blank=True, help_text='Optional publication/report number.', max_length=50)),
                ('eyebrow', models.CharField(blank=True, help_text='Short label displayed above the report title.', max_length=150)),
                ('summary', models.TextField(blank=True, help_text='Short description used on the Reports library page.')),
                ('abstract', ckeditor.fields.RichTextField(blank=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='report_covers/')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='report_pdfs/')),
                ('theme', models.CharField(choices=[('standard', 'Standard Intelligence'), ('agriculture', 'Agriculture & Trade'), ('economics', 'Economics & Markets'), ('policy', 'Policy & Governance'), ('statistics', 'Statistics & Data'), ('development', 'Development'), ('technology', 'Technology & Innovation')], default='standard', max_length=30)),
                ('featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-publication_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1)),
                ('heading', models.CharField(max_length=250)),
                ('content', ckeditor.fields.RichTextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='report_section_images/')),
                ('image_caption', models.CharField(blank=True, max_length=300)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='app.report')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
