# Generated by Django 4.2.10 on 2026-09-03 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_enroll_report_reportsection'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='document_file',
            field=models.FileField(blank=True, help_text='Optional editable publication file such as DOC or DOCX.', null=True, upload_to='report_documents/'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='Optional final report in PDF format.', null=True, upload_to='report_pdfs/'),
        ),
        migrations.AlterField(
            model_name='report',
            name='theme',
            field=models.CharField(choices=[('standard', 'Standard Intelligence'), ('agriculture', 'Agriculture & Trade'), ('economics', 'Economics & Markets'), ('policy', 'Policy & Governance'), ('public_affairs', 'Public Affairs'), ('humanitarian', 'Humanitarian Research'), ('market_research', 'Market Research'), ('statistics', 'Statistics & Data'), ('development', 'Development'), ('technology', 'Technology & Innovation')], default='standard', max_length=30),
        ),
    ]
