# Generated by Django 4.2.10 on 2026-09-03 21:35

import app.models
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_report_document_file_alter_journal_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IJIRISubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_reference', models.CharField(blank=True, editable=False, max_length=30, unique=True)),
                ('paper_title', models.CharField(help_text='Maximum 15 words.', max_length=300, validators=[app.models.validate_title_15_words])),
                ('abstract', models.TextField(help_text='Maximum 300 words.', validators=[app.models.validate_abstract_300_words])),
                ('research_category', models.CharField(choices=[('business_management', 'Business & Management'), ('economics_development', 'Economics & Development'), ('public_policy_governance', 'Public Policy & Governance'), ('social_sciences', 'Social Sciences'), ('education', 'Education'), ('health', 'Health & Wellbeing'), ('environment_climate', 'Environment & Climate Change'), ('agriculture_food', 'Agriculture & Food Systems'), ('technology_data', 'Technology, Data & Innovation'), ('market_research', 'Market Research & Consumer Insights'), ('interdisciplinary', 'Interdisciplinary Research'), ('other', 'Other')], max_length=50)),
                ('keywords', models.CharField(help_text='Provide 3–5 relevant keywords separated by commas.', max_length=500, validators=[app.models.validate_keywords_3_to_5])),
                ('author_details', models.TextField(help_text='Provide all author names, affiliations, countries and email addresses.')),
                ('corresponding_author_name', models.CharField(max_length=200)),
                ('corresponding_author_email', models.EmailField(max_length=254)),
                ('country', models.CharField(max_length=120)),
                ('mobile_number', models.CharField(blank=True, help_text='Optional. Include international country code, for example +255...', max_length=40, validators=[django.core.validators.RegexValidator(message='Enter a valid mobile number including the international country code.', regex='^\\+?[0-9\\s\\-\\(\\)]{7,30}$')])),
                ('orcid', models.CharField(blank=True, help_text='Optional ORCID identifier.', max_length=50)),
                ('manuscript_file', models.FileField(help_text='Accepted formats: DOC or DOCX. Maximum file size: 6 MB.', upload_to='ijiri_submissions/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['doc', 'docx']), app.models.validate_max_6mb])),
                ('originality_confirmed', models.BooleanField(default=False, verbose_name='Originality declaration confirmed')),
                ('similarity_confirmed', models.BooleanField(default=False, verbose_name='Similarity below 18% confirmed')),
                ('ai_threshold_confirmed', models.BooleanField(default=False, verbose_name='AI content below 15% confirmed')),
                ('ai_use_acknowledged', models.BooleanField(default=False, verbose_name='AI use disclosure acknowledged')),
                ('apa7_confirmed', models.BooleanField(default=False, verbose_name='APA 7th Edition compliance confirmed')),
                ('authorisation_confirmed', models.BooleanField(default=False, verbose_name='Corresponding author submission authority confirmed')),
                ('declaration_confirmed', models.BooleanField(default=False, verbose_name='General submission declaration confirmed')),
                ('ai_use_statement', models.TextField(blank=True, help_text='Describe any use of generative AI in preparing the manuscript, if applicable.')),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('editorial_check', 'Editorial Check'), ('deep_review', 'Deep Review'), ('editorial_decision', 'Editorial Decision'), ('peer_review', 'Peer Review'), ('revision', 'Revision Required'), ('revision_review', 'Revision Review'), ('approved', 'Approved'), ('galley_proof', 'Galley Proof'), ('published', 'Published'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='submitted', max_length=40)),
                ('internal_notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status_updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'IJIRI Manuscript Submission',
                'verbose_name_plural': 'IJIRI Manuscript Submissions',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
