# Generated by Django 4.2.10 on 2026-09-04 08:46

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_ijirisubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='ijirisubmission',
            name='subtitle',
            field=models.CharField(blank=True, help_text='Optional subtitle or case context. Maximum 10 words.', max_length=300, validators=[app.models.validate_subtitle_10_words]),
        ),
    ]
