# Generated by Django 4.2.10 on 2026-09-14 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_ijirisubmission_subtitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_reference', models.CharField(blank=True, editable=False, max_length=30, unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_number', models.CharField(max_length=40)),
                ('country', models.CharField(max_length=100)),
                ('organisation', models.CharField(blank=True, max_length=200)),
                ('role_or_academic_level', models.CharField(max_length=200)),
                ('training_area', models.CharField(choices=[('research_fundamentals', 'Research Fundamentals'), ('research_design_methods', 'Research Design & Methods'), ('proposal_development', 'Proposal Development'), ('data_collection_techniques', 'Data Collection Techniques'), ('quantitative_analysis', 'Quantitative Analysis'), ('qualitative_analysis', 'Qualitative Analysis')], max_length=50)),
                ('learning_expectation', models.TextField(blank=True)),
                ('training_fee', models.PositiveIntegerField(default=280000, editable=False)),
                ('status', models.CharField(choices=[('pending_payment', 'Pending Payment'), ('payment_confirmed', 'Payment Confirmed'), ('access_sent', 'Access Sent'), ('cancelled', 'Cancelled')], default='pending_payment', max_length=30)),
                ('payment_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('training_access_link', models.URLField(blank=True, max_length=500)),
                ('access_email_sent', models.BooleanField(default=False)),
                ('internal_notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Training Application',
                'verbose_name_plural': 'Training Applications',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
