# Generated by Django 4.2.10 on 2026-09-15 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0016_trainingapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingapplication',
            name='learner_user',
            field=models.ForeignKey(blank=True, help_text='Investmetrics Learning account assigned to this training application.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_applications', to=settings.AUTH_USER_MODEL),
        ),
    ]
