# Generated by Django 4.2.10 on 2026-09-20 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_trainingapplication_learner_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingapplication',
            name='training_pathway',
            field=models.CharField(choices=[('research', 'Research & Evidence'), ('professional', 'General Professional Work')], default='research', max_length=30),
        ),
        migrations.AlterField(
            model_name='trainingapplication',
            name='training_area',
            field=models.CharField(choices=[('research_fundamentals', 'Research Fundamentals'), ('research_design_methods', 'Research Design & Methods'), ('proposal_development', 'Proposal Development'), ('data_collection_techniques', 'Data Collection Techniques'), ('quantitative_analysis', 'Quantitative Analysis'), ('qualitative_analysis', 'Qualitative Analysis'), ('ai_client_stakeholder', 'AI for Client & Stakeholder Facing Work'), ('ai_leadership_management', 'AI for Leadership & Management'), ('ai_operations_delivery', 'AI for Operations & Delivery')], max_length=50),
        ),
    ]
